/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JToggleButton;

/**
 *
 * @author Ayler
 */
public class OrdenacaoView extends javax.swing.JFrame {

    /**
     * Creates new form OrdenacaoView
     */
    public OrdenacaoView() {
        initComponents();
        this.buttonGroup1.add(this.getRbtnCrescente());
        this.buttonGroup1.add(this.getRbtnDecrescente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSemOrdenados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstOrdenados = new javax.swing.JList<>();
        cmbMetodo = new javax.swing.JComboBox<>();
        rbtnCrescente = new javax.swing.JRadioButton();
        rbtnDecrescente = new javax.swing.JRadioButton();
        lblTempo = new javax.swing.JLabel();
        txtTempo = new javax.swing.JLabel();
        lblElementosASeremOrdenados = new javax.swing.JLabel();
        lblElementosOrdenados = new javax.swing.JLabel();
        Ordem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnCarregarArquivo = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstSemOrdenados);

        jScrollPane2.setViewportView(lstOrdenados);

        rbtnCrescente.setText("Crescente");

        rbtnDecrescente.setText("Decrescente");

        lblTempo.setText("0 ms");

        txtTempo.setText("Tempo:");

        lblElementosASeremOrdenados.setText("Elementos a serem ordenados");

        lblElementosOrdenados.setText("Elementos ordenados");

        Ordem.setText("Ordem");

        jLabel4.setText("Método ordenação");

        btnLimpar.setText("Limpar");

        btnCarregarArquivo.setText("Carregar Arquivo...");

        btnOrdenar.setText("Ordenar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarregarArquivo))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnCrescente)
                                    .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ordem)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnOrdenar)
                                        .addComponent(rbtnDecrescente))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnLimpar))))
                    .addComponent(lblElementosASeremOrdenados))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(txtTempo)
                        .addGap(18, 18, 18)
                        .addComponent(lblTempo)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblElementosOrdenados)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblElementosASeremOrdenados, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblElementosOrdenados, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Ordem)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbtnCrescente)
                            .addGap(2, 2, 2)
                            .addComponent(rbtnDecrescente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOrdenar)
                            .addGap(12, 12, 12))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTempo)
                        .addComponent(txtTempo)
                        .addComponent(btnLimpar))
                    .addComponent(btnCarregarArquivo))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCarregarArquivo() {
        return btnCarregarArquivo;
    }

    public JButton getBtnOrdenar() {
        return btnOrdenar;
    }

    public JButton getBtnLimpar() {
        return btnLimpar;
    }

    public JComboBox<String> getCmbMetodo() {
        return cmbMetodo;
    }

    public JLabel getLblTempo() {
        return lblTempo;
    }

    public JList<Double> getLstOrdenados() {
        return lstOrdenados;
    }

    public JList<Double> getLstSemOrdenados() {
        return lstSemOrdenados;
    }

    public JRadioButton getRbtnCrescente() {
        return rbtnCrescente;
    }

    public JRadioButton getRbtnDecrescente() {
        return rbtnDecrescente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ordem;
    private javax.swing.JButton btnCarregarArquivo;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbMetodo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblElementosASeremOrdenados;
    private javax.swing.JLabel lblElementosOrdenados;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JList<Double> lstOrdenados;
    private javax.swing.JList<Double> lstSemOrdenados;
    private javax.swing.JRadioButton rbtnCrescente;
    private javax.swing.JRadioButton rbtnDecrescente;
    private javax.swing.JLabel txtTempo;
    // End of variables declaration//GEN-END:variables
}
